jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
servlet:
    multipart:
      max-file-size: 50MB
spring:
    data:
      mongodb:
        uri: mongodb://localhost/admin
        username: ${dbuser:admin}
        password: ${dbpassword:admin}
app:
  upload:
    path: ${UPLOAD_PATH:?Can`t find upload path}
  auth:
    secret: ${JWT_SECRET:Secret1234}
    token_expiration: 864000000
server:
  port: 10000
